// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnacsnpcilvrqhmlzgel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuYWNzbnBjaWx2cnFobWx6Z2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzU5MzEsImV4cCI6MjA3MzQ1MTkzMX0.-RckGMAASJFT8L9tHkd9UjyRb-XmkG5JK7DKYJ5Xokk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});